# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi
# setting workon home and virtualenvwrapper
# export WORKON_HOME=~/envs

export TMPDIR=/tmp
export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3
# purposely use the the binary as to not confuse paths at all
alias mkvirtualenv2='mkvirtualenv -p /usr/bin/python2'
source /usr/bin/virtualenvwrapper.sh


#teamocil autocompletion
compctl -g '~/.teamocil/*(:t:r)' teamocil

source $HOME/.zshrc.local
PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting





bindkey '^R' history-incremental-search-backward
