# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi
# setting workon home and virtualenvwrapper
export WORKON_HOME=~/envs
source /usr/local/bin/virtualenvwrapper.sh


#teamocil autocompletion
compctl -g '~/.teamocil/*(:t:r)' teamocil

source $HOME/.zshrc.local
PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
